work-lah-cms/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'Auth\LoginController@index');
Route::resource('register', 'Auth\RegisterController');

Route::group(['middleware' => 'auth'], function () {
    // Home
    Route::get('home', 'HomeController@index')->name('home');
    Route::get('logout', 'HomeController@logout')->name('logout');

    // Resources
    Route::resources([
    	'profile' => 'ProfileController',
        'job' => 'JobController',
    ]);
});

work-lah-cms/app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * Table name
     * 
     * @var string
     */
    protected $table = 'user';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'password', 'email', 'uuid',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];
}

work-lah-cms/app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

work-lah-cms/app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\User;
use Illuminate\Support\Facades\Auth;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $user = User::find(Auth::user()->id);

        return view('home', compact('user'));
    }

    /**
     * Log out
     *
     * @return \Illuminate\Http\Response
     */
    public function logout()
    {
        Auth::logout();
        return view('auth.login');
    }
}

work-lah-cms/app/Http/Controllers/JobController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Handle;
use App\Traits\Firebase;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class JobController extends Controller
{
    use Firebase;

    private $tableName = 'jobs/';

    /**
     * Show profile
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $uuid = Auth::user()->uuid;
        $jobs = $this->getFirebaseTable($this->tableName)
            ->orderByChild('companyID')
            ->equalTo($uuid)
            ->getValue();

        return view('job.index', compact('jobs'));
    }

    /**
     * Edit job
     *
     * @param $id
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function edit($id)
    {
        $job = $this->getFirebaseTable($this->tableName . $id)
            ->getValue();

        return view('job.edit', compact(['id', 'job']));
    }

    /**
     * Update job
     *
     * @param $request
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $uuid)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|string',
            'location' => 'required|string',
            'latitude' => 'required|string',
            'longitude' => 'required|string',
            'existedImage' => 'string'
        ]);

        $data = [
            'companyName' => $request->input('name'),
            'email' => $request->input('email'),
            'location' => $request->input('location'),
            'logo' => (!$request->input('imagePath')) ? $request->input('existedImage') : $request->input('imagePath'),
            'coordinates' => [
                'latitude' => $request->input('latitude'),
                'longitude' => $request->input('longitude')
            ]
        ];

        try {
            $this->getFirebaseReference()->update([
                $this->tableName . $uuid => $data
            ]);

        } catch (Exception $e) {
            Handle::error('Failed updating profile', $e, $request);
            return redirect('profile');
        }

        Handle::success('Successfully updated profile', $request);
        return redirect('profile');
    }
}

work-lah-cms/app/Http/Controllers/ProfileController.php
<?php

namespace App\Http\Controllers;

use App\Helpers\Handle;
use App\Traits\Firebase;
use Exception;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class ProfileController extends Controller
{
    use Firebase;

    private $tableName = 'companies/';

    /**
     * Show profile
     *
     * @return \Illuminate\Contracts\View\Factory|\Illuminate\View\View
     */
    public function index()
    {
        $uuid = Auth::user()->uuid;
        $company = $this->getFirebaseTable($this->tableName . $uuid)->getValue();

        return view('profile', compact(['company', 'uuid']));
    }

    /**
     * Update profile
     *
     * @param $request
     * @param $uuid
     * @return \Illuminate\Http\RedirectResponse|\Illuminate\Routing\Redirector
     */
    public function update(Request $request, $uuid)
    {
        $request->validate([
            'name' => 'required|string',
            'email' => 'required|string',
            'location' => 'required|string',
            'latitude' => 'required|string',
            'longitude' => 'required|string',
            'existedImage' => 'string'
        ]);

        $data = [
            'companyName' => $request->input('name'),
            'email' => $request->input('email'),
            'location' => $request->input('location'),
            'logo' => (!$request->input('imagePath')) ? $request->input('existedImage') : $request->input('imagePath'),
            'coordinates' => [
                'latitude' => $request->input('latitude'),
                'longitude' => $request->input('longitude')
            ]
        ];

        try {
            $this->getFirebaseReference()->update([
                $this->tableName . $uuid => $data
            ]);

        } catch (Exception $e) {
            Handle::error('Failed updating profile', $e, $request);
            return redirect('profile');
        }

        Handle::success('Successfully updated profile', $request);
        return redirect('profile');
    }
}

work-lah-cms/resources/views/home.blade.php
@extends('layouts.app')

@section('title', 'Home')

@section('stylesheets')
@endsection

@section('breadcrumb')
<h5 class="breadcrumbs-title">Home</h5>
<ol class="breadcrumbs">
    <li><a href="{{ route('home') }}">Home</a></li>
</ol>
@endsection

@section('content')
<p class="caption">Hello, {{ ucfirst($user->name) }}!</p>
<div class="divider"></div>
@endsection

@section('scripts')
<script type="text/javascript">
	$(function() {
		$('#menu-home').addClass('active');
	})
</script>
@endsection

work-lah-cms/resources/views/job/edit.blade.php
@extends('layouts.app')

@section('title', 'Edit Job')

@section('stylesheets')
@endsection

@section('breadcrumb')
<h5 class="breadcrumbs-title">Edit Job</h5>
<ol class="breadcrumbs">
    <li><a href="{{ route('job.index') }}">Jobs</a></li>
	<li><a href="#">Edit Job</a></li>
</ol>
@endsection

@section('content')
<p class="caption">Job's detail will attract more professional applicant.</p>
<div class="divider"></div>

<div class="row">
	<div class="col s12 m12 l12">
        <div class="card-panel">
        	<div class="row">
            	<form id="profile-form" action="{{ url('job/' . $id) }}" class="col s12" method="POST"  enctype="multipart/form-data">
            		@csrf
            		{{ method_field('PUT') }}

	            	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-social-location-city prefix"></i>
	                		<input id="role" name="role" type="text" class="validate" value="{{ $job['role'] }}" required>
	                		<label for="role">Role</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                  		<i class="mdi-communication-email prefix"></i>
	                  		<input id="category" name="category" type="text" class="validate" value="{{ $job['category'] }}" required>
	                  		<label for="category">Category</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-maps-map prefix"></i>
	                		<input id="salary" name="salary" type="number" class="validate" value="{{ $job['salary'] }}" required>
	                		<label for="salary">Salary</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-maps-pin-drop prefix"></i>
	                		<input id="type" name="type" type="text" class="validate" value="{{ $job['type'] }}" required>
	                		<label for="type">Type</label>
	                	</div>
	              	</div>
					<div class="row">
						<div class="input-field col s12">
							<i class="mdi-maps-pin-drop prefix"></i>
							<textarea id="description" name="description" type="text" class="materialize-textarea validate" required>{{ $job['description'] }}</textarea>
							<label for="description">Description</label>
						</div>
					</div>
					<div class="row">
						<div class="input-field col s12">
							<i class="mdi-maps-pin-drop prefix"></i>
							<input id="responsibilities" name="responsibility" type="text" class="validate" required>
							<label for="responsibilities">Responsibilities</label>
						</div>
					</div>
	                <div class="row">
	                  	<div class="input-field col s12">
	                    	<button class="btn cyan waves-effect waves-light right" type="button" id="updateBtn" name="action">Update
	                      		<i class="mdi-action-input right"></i>
	                    	</button>
	                  	</div>
	                </div>
	            </div>
	        </form>
	    </div>
    </div>
</div>
@endsection

@section('scripts')
<script type="text/javascript">
	$(function() {
		$('#menu-jobs').addClass('active')
	})
</script>
@endsection

work-lah-cms/resources/views/job/index.blade.php
@extends('layouts.app')

@section('title', 'Job List')

@section('stylesheets')
<link href="{{ asset('js/plugins/data-tables/css/jquery.dataTables.min.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
<link href="{{ asset('js/plugins/sweetalert/dist/sweetalert.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('breadcrumb')
<h5 class="breadcrumbs-title">Jobs</h5>
<ol class="breadcrumbs">
    <li><a href="{{ route('job.index') }}">Jobs</a></li>
</ol>
@endsection

@section('content')
<p class="caption">Job List</p>
<div class="divider"></div>
<div id="table-datatables">
	<div class="row">
		<div class="col s12 m12 l12">
			<table id="data-table-simple" class="responsive-table display hoverable" cellspacing="0">
				<thead>
				<tr>
					<th>Role</th>
					<th>Category</th>
					<th>Salary</th>
					<th>Date Posted</th>
					<th>Type</th>
					<th>Actions</th>
				</tr>
				</thead>

				<tbody>
				@foreach($jobs as $key => $job)
					<tr>
						<td>{{ $job['role'] }}</td>
						<td>{{ $job['category'] }}</td>
						<td>{{ $job['salary'] }}</td>
						<td>{{ $job['datePosted'] }}</td>
						<td>{{ $job['type'] }}</td>
						<td>
							<a href="{{ route('job.edit', $key) }}" class="tooltipped edit-row col l2" data-position="top" data-delay="50" data-tooltip="Edit"><i class="mdi-editor-mode-edit"></i></a>
							<a href="#" class="tooltipped remove-row col l2" data-toggle="tooltip" data-id="{{ $key }}" data-name="{{ $job['role'] }}" data-position="top" data-delay="50" data-tooltip="Delete"><i class="mdi-action-delete"></i></a>
						</td>
					</tr>
				@endforeach
				</tbody>
			</table>
		</div>
	</div>
	<div style="display: none">
		<form id="delete-form" method="POST">
			@csrf
			{{ method_field('delete') }}
		</form>
	</div>
</div>
@endsection

@section('scripts')
<script type="text/javascript" src="{{ asset('js/plugins/data-tables/js/jquery.dataTables.min.js') }}"></script>
<script type="text/javascript" src="{{ asset('js/plugins/data-tables/data-tables-script.js') }}"></script>

<script type="text/javascript" src="{{ asset('js/plugins/sweetalert/dist/sweetalert.min.js') }}"></script>

<script>
	$(function() {
		$('#menu-jobs').addClass('active')

		$('.tooltipped').tooltip({
			delay: 50
		})

		$('#data-table-simple tbody').on('click', '.remove-row', function (e) {
			e.preventDefault();
			let id = $(this).data('id');
			let name = $(this).data('name');

			swal({
				title: "Delete Confirmation",
				text: "Do you want to delete " + name + "?",
				showCancelButton: true,
				confirmButtonText: "Yes",
				cancelButtonText: "No"
			}).then(function () {
				$('#delete-form').attr('action', '{{ route("job.index") }}/' + id).submit();
			}).catch(swal.noop);
		});
	})
</script>
@endsection

work-lah-cms/resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">

<!--================================================================================
	Item Name: Materialize - Material Design Admin Template
	Version: 3.0
	Author: GeeksLabs
	Author URL: http://www.themeforest.net/user/geekslabs
================================================================================ -->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1.0, user-scalable=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>@yield('title') | Worklah Company Panel</title>

    <!-- Favicon-->
    <link rel="icon" href="{{ asset('images/logo-worklah.png') }}">

    <!-- CORE CSS-->
    <link href="{{ asset('css/materialize.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
    <link href="{{ asset('css/style.css') }}" type="text/css" rel="stylesheet" media="screen,projection">

    @yield('stylesheets')

    <!-- INCLUDED PLUGIN CSS ON THIS PAGE -->
    <link href="{{ asset('js/plugins/perfect-scrollbar/perfect-scrollbar.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
</head>

<body>
<!-- Start Page Loading -->
<div id="loader-wrapper">
    <div id="loader"></div>
    <div class="loader-section section-left"></div>
    <div class="loader-section section-right"></div>
</div>
<!-- End Page Loading -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START HEADER -->
<header id="header" class="page-topbar">
    <!-- start header nav-->
    <div class="navbar-fixed">
        <nav class="navbar-color">
            <div class="nav-wrapper">
                <ul class="left" style="padding: 1rem;">
                    <li><h1 class="logo-wrapper">
                        <a href="{{ route('home') }}" class="brand-logo darken-1" style="padding: 0;"><img src="{{ asset('images/logo-worklah-white.png') }}" alt="Worklah" style="height: 40px; width: auto;"></a>
                    </h1></li>
                </ul>
            </div>
        </nav>
    </div>
    <!-- end header nav-->
</header>
<!-- END HEADER -->

<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START MAIN -->
<div id="main">
    <!-- START WRAPPER -->
    <div class="wrapper">

        <!-- START LEFT SIDEBAR NAV-->
        <aside id="left-sidebar-nav">
            <ul id="slide-out" class="side-nav fixed leftside-navigation">
                <li class="user-details cyan darken-1">
                    <div class="row">
                        <div class="col col s4 m4 l4">
                            {{-- <img src="{{ asset($user->image) }}" alt="" class="circle responsive-img valign profile-image"> --}}
                        </div>
                        <div class="col col s8 m8 l8">
                            <a class="btn-flat dropdown-button waves-effect waves-light white-text profile-btn" href="#" data-activates="profile-dropdown">{{ Auth::user()->name }}</a>
                            <p class="user-roal">{{ Auth::user()->email }}</p>
                        </div>
                    </div>
                </li>
                <li id="menu-home"><a href="{{ route('home') }}" class="waves-effect waves-cyan"><i class="mdi-action-home"></i> Home</a></li>
                <li id="menu-profile"><a href="{{ route('profile.index') }}" class="waves-effect waves-cyan"><i class="mdi-social-domain"></i> Company Profile</a></li>
                <li id="menu-jobs"><a href="{{ route('job.index') }}" class="waves-effect waves-cyan"><i class="mdi-action-wallet-travel"></i> Jobs</a></li>
                <li><a href="{{ route('logout') }}" class="waves-effect waves-cyan"><i class="mdi-action-settings-power"></i> Logout</a></li>
            </ul>
            <a href="#" data-activates="slide-out" class="sidebar-collapse btn-floating btn-medium waves-effect waves-light hide-on-large-only cyan"><i class="mdi-navigation-menu"></i></a>
        </aside>
        <!-- END LEFT SIDEBAR NAV-->

        <!-- //////////////////////////////////////////////////////////////////////////// -->

        <!-- START CONTENT -->
        <section id="content">
            <!--breadcrumbs start-->
            <div id="breadcrumbs-wrapper">
                <div class="container">
                    <div class="row">
                        <div class="col s12 m12 l12">
                            @yield('breadcrumb')
                        </div>
                    </div>
                </div>
            </div>
            <!--breadcrumbs end-->

            <!--start container-->
            <div class="container">
                <div class="section">
                    @yield('content')
                </div>
            </div>
            <!--end container-->
        </section>
        <!-- END CONTENT -->

    </div>
    <!-- END WRAPPER -->

</div>
<!-- END MAIN -->



<!-- //////////////////////////////////////////////////////////////////////////// -->

<!-- START FOOTER -->
<footer class="page-footer">
    <div class="footer-copyright">
        <div class="container">
            <span style="margin-left: 240px">2018 Worklah by <a class="grey-text text-lighten-4" href="#">A-Onegaishimasu</a></span>
            <span class="right"> Theme by <a class="grey-text text-lighten-4" href="http://geekslabs.com/">GeeksLabs</a></span>
        </div>
    </div>
</footer>
<!-- END FOOTER -->


<!-- ================================================
Scripts
================================================ -->

<!-- jQuery Library -->
<script type="text/javascript" src="{{ asset('js/plugins/jquery-1.11.2.min.js') }}"></script>
<!--materialize js-->
<script type="text/javascript" src="{{ asset('js/materialize.js') }}"></script>
<!--scrollbar-->
<script type="text/javascript" src="{{ asset('js/plugins/perfect-scrollbar/perfect-scrollbar.min.js') }}"></script>

<!--plugins.js - Some Specific JS codes for Plugin Settings-->
<script type="text/javascript" src="{{ asset('js/plugins.js') }}"></script>

<script>
    $(function() {
        if ('{{ session('status') }}' !== null) {
            Materialize.toast('{{ session('msg') }}', 3000)
        }
        
        @if ($errors->any())
            @foreach ($errors->all() as $error)
                Materialize.toast('{{ $error }}', 3000)
            @endforeach
        @endif
    });
</script>

@yield('scripts')

</body>

</html>

work-lah-cms/resources/views/profile.blade.php
@extends('layouts.app')

@section('title', 'Company Profile')

@section('stylesheets')
<link href="{{ asset('js/plugins/magnific-popup/magnific-popup.css') }}" type="text/css" rel="stylesheet" media="screen,projection">
@endsection

@section('breadcrumb')
<h5 class="breadcrumbs-title">Company Profile</h5>
<ol class="breadcrumbs">
    <li><a href="{{ route('profile.index') }}">Company Profile</a></li>
</ol>
@endsection

@section('content')
<div class="masonry-gallery-wrapper" style="right: 1.5rem; top: 6rem">
	<div class="popup-gallery">
		<div class="gallary-sizer"></div>
		<div class="gallary-item"><a href="{{ $company['logo'] }}" title="Logo"><img src="{{ $company['logo'] }}" style="height: 150px; width: auto; right: 1.5rem;"></a></div>
	</div>
</div>
<p class="caption">Profile defines professionality.</p>
<div class="divider"></div>

<div class="row">
	<div class="col s12 m12 l12">
        <div class="card-panel">
        	<div class="row">
            	<form id="profile-form" class="col s12" method="POST"  enctype="multipart/form-data">
            		@csrf
            		{{ method_field('PUT') }}
            		<input name='existedImage' value="{{ $company['logo'] }}" hidden>

	            	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-social-location-city prefix"></i>
	                		<input id="name" name="name" type="text" class="validate" value="{{ $company['companyName'] }}" required>
	                		<label for="name">Company Name</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                  		<i class="mdi-communication-email prefix"></i>
	                  		<input id="email" name="email" type="email" class="validate" value="{{ $company['email'] }}" required>
	                  		<label for="email">Email</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-maps-map prefix"></i>
	                		<input id="location" name="location" type="text" class="validate" value="{{ $company['location'] }}" required>
	                		<label for="location">Location</label>
	                	</div>
	              	</div>
	              	<div class="row">
	                	<div class="input-field col s12">
	                		<i class="mdi-maps-pin-drop prefix"></i>
	                		<input id="longitude" name="longitude" type="text" class="validate" value="{{ $company['coordinates']['longitude'] }}" required>
	                		<label for="longitude">Longitude</label>
	                	</div>
	              	</div>
					<div class="row">
						<div class="input-field col s12">
							<i class="mdi-maps-pin-drop prefix"></i>
							<input id="latitude" name="latitude" type="text" class="validate" value="{{ $company['coordinates']['latitude'] }}" required>
							<label for="latitude">latitude</label>
						</div>
					</div>
	              	<div class="row">
	              		<div class="file-field input-field col s6">
	              			<i class="mdi-image-photo prefix"></i>
	              			<input class="file-path validate" type="text" id="image" />
	              			<input type="text" id="imagePath" name="imagePath" hidden />
	                        <label for="image">New Company Logo</label>
	                        <div class="btn blue waves-effect waves-light">
	                        	<span>Upload new logo</span>
	                        	<input type="file" id="uploadedImage" />
	                        </div>
	                    </div>
		            </div>
	                <div class="row">
	                  	<div class="input-field col s12">
	                    	<button class="btn cyan waves-effect waves-light right" type="button" id="updateBtn" name="action">Update
	                      		<i class="mdi-action-input right"></i>
	                    	</button>
	                  	</div>
	                </div>
	            </div>
	        </form>
	    </div>
    </div>
</div>
@endsection

@section('scripts')
<script src="{{ asset('js/plugins/masonry.pkgd.min.js') }}"></script>
<script src="{{ asset('js/plugins/imagesloaded.pkgd.min.js') }}"></script>    
<script type="text/javascript" src="{{ asset('js/plugins/magnific-popup/jquery.magnific-popup.min.js') }}"></script>

<!--firebase.js - Add Firebase to web-->
<script src="https://www.gstatic.com/firebasejs/5.5.9/firebase.js"></script>

<script type="text/javascript">
	var config = {
        apiKey: "{{ config('services.firebase.api_key') }}",
        authDomain: "{{ config('services.firebase.auth_domain') }}",
        databaseURL: "{{ config('services.firebase.database_url') }}",
        projectId: "{{ config('services.firebase.project_id') }}",
        storageBucket: "{{ config('services.firebase.storage_bucket') }}",
    };
    firebase.initializeApp(config);

	$(function() {
		$('#menu-profile').addClass('active')

		let $containerGallery = $(".masonry-gallery-wrapper");
    	$containerGallery.imagesLoaded(function() {
        	$containerGallery.masonry({
            	itemSelector: '.gallary-item img',
           		columnWidth: '.gallary-sizer',
           		isFitWidth: true
    		});
      	});

      	$('.popup-gallery').magnificPopup({
        	delegate: 'a',
	        type: 'image',
	        closeOnContentClick: true,    
	        fixedContentPos: true,
	        tLoading: 'Loading image #%curr%...',
	        mainClass: 'mfp-img-mobile mfp-no-margins mfp-with-zoom',
	        gallery: {
	        	enabled: true,
	          	navigateByImgClick: true,
	          	preload: [0,1] // Will preload 0 - before current, and 1 after the current image
	        },
	        image: {
	          	verticalFit: true,
	          	tError: '<a href="%url%">The image #%curr%</a> could not be loaded.',
	          	titleSrc: function(item) {
	            	return item.el.attr('title') + '<small>by Marsel Van Oosten</small>';
	          	},
	        	zoom: {
		          	enabled: true,
		          	duration: 300 // don't foget to change the duration also in CSS
		        }
        	}
      	});

      	$('button#updateBtn').on('click', function () {
	      	let file = $('#uploadedImage').get(0).files[0]

	      	if (file !== undefined) {
		      	let ref = firebase.storage().ref()
				let name = 'jobs/avatar-' + file.name

				Materialize.toast('Uploading your company logo', 2000)
				
				ref.child(name).put(file)
					.then(snapshot => snapshot.ref.getDownloadURL())
				  	.then((url) => {
				  		console.log(url)
				  		$('input#imagePath').attr('value', url)
				  		$('#profile-form').attr('action', "{{ url('profile/' . $uuid) }}").submit()
				  	})
				  	.catch((error) => {
				  		Materialize.toast('Failed uploading logo', 3000)
				  		console.log(error)
				  	});
			} else {
				$('#profile-form').attr('action', "{{ url('profile/' . $uuid) }}").submit()
			}
	  	});
	})
</script>
@endsection